const isdebug = true;
const appStartTime = new Date().getTime();

// var thePlayerr = document.getElementsByTagName("retro-player")[0];
// console.log(thePlayerr);

var thePlayer = document.getElementsByTagName("body")[0];
var bgLayer = document.createElement("div");
bgLayer.setAttribute("id", "myBackground");
bgLayer.setAttribute("class", "bgLayer");
thePlayer.appendChild(bgLayer);
var fgLayer = document.createElement("div");
fgLayer.setAttribute("id", "myForeground");
fgLayer.setAttribute("class", "fgLayer");
thePlayer.appendChild(fgLayer);
var titleLayer = document.createElement("div");
titleLayer.setAttribute("id", "myTitleScreen");
titleLayer.setAttribute("class", "titlescreen");
var titleH1 = document.createElement("h3");
titleH1.setAttribute("class", "myhead h1");
titleLayer.appendChild(titleH1);
var titleH3 = document.createElement("h3");
titleH3.setAttribute("class", "myhead h3");
titleLayer.appendChild(titleH3);
thePlayer.appendChild(titleLayer);
var splashLayer = document.createElement("div");
splashLayer.setAttribute("id", "mySplashScreen");
splashLayer.setAttribute("class", "splash off");
thePlayer.appendChild(splashLayer);

var theShelf = document.createElement("div");
theShelf.setAttribute("id", "myPlayerShelf");
theShelf.setAttribute("class", "shelfContainer");
thePlayer.appendChild(theShelf);
var theRemote = document.createElement("div");
theRemote.setAttribute("id", "myPlayerRemote");
theRemote.setAttribute("class", "remoteContainer");
thePlayer.appendChild(theRemote);
var theTv = document.createElement("div");
theTv.setAttribute("id", "myPlayerTv");
theTv.setAttribute("class", "tvContainer");
thePlayer.appendChild(theTv);
var theVcr = document.createElement("div");
theVcr.setAttribute("id", "myPlayerVcr");
theVcr.setAttribute("class", "vcrContainer");
thePlayer.appendChild(theVcr);
var thePoster = document.createElement("div");
thePoster.setAttribute("id", "myPlayerPoster");
thePoster.setAttribute("class", "posterContainer");
thePlayer.appendChild(thePoster);
